spring:
  application:
    name: mybatis
  #数据库配置
  datasource:
    druid:
      # StatViewServlet 配置
      stat-view-servlet:
        enabled: true
        # 访问路径为 /druid时，跳转到 StatViewServlet
        url-pattern: /druid/*
        # 是否能够重置数据
        reset-enable: false
        # 设置访问的账号密码
        login-username: root
        login-password: 123456
        # IP 白名单
        allow: 127.0.0.1
        # IP 黑名单（共同存在时，deny优先于allow）
        # deny: 172.21.1.100

      # WebStatFilter配置
      web-stat-filter:
        enabled: true
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤的格式
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      # 配置StatFilter
      filter:
        stat:
          log-slow-sql: true

    dynamic:
      #这个是全局配置，下面的各个数据源可以单独配置，并覆盖这个全局配置
      druid:
        # 连接池配置
        initial-size: 5
        min-idle: 5
        max-active: 20
        # 连接等待超时的时间
        max-wait: 30000
        # 配置检测可以关闭的空闲连接间隔时间
        time-between-eviction-runs-millis: 60000
        # 配置连接池中的最小生存时间
        min-evictable-idle-time-millis: 300000
        validation-query: select 1 from dual
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        # 打开 PSCache，并且指定每个连接上 PSCache 的大小
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        # 配置监控统计拦截的 filters，去掉后监控见面sql无法统计，'wall'用于防火墙
        filters: stat,wall,slf4j
        # 合并多个DruidDataSource的监控数据
        use-global-data-source-stat: true
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录  connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
        stat:
          merge-sql: true
          log-slow-sql: true
          slow-sql-millis: 500
      datasource:
        master:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://47.106.95.195:3306/spring?useUnicode=true&characterEncoding=utf-8&useSSL=false
          username: root
          password: 123456
        slave:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://47.106.95.195:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
          username: root
          password: 123456

# mybatis plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.we.springboot.mybatis.bean
  configuration:
    map-underscore-to-camel-case: true #属性支持驼峰命名
    callSettersOnNulls: true
    cache-enabled: false
  global-config:
    db-config:
      id-type: auto #实体类上配置能覆盖全局配置
      logic-delete-value: 1 #逻辑已删除值
      logic-not-delete-value: 0 #逻辑未删除值


# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

# 日志
logging:
  level:
    com.we.springboot.mybatis.dao: trace

