spring:
  application:
    name: redis
  datasource:
    schema: classpath:db/department.sql
    initialization-mode: never
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.106.95.195/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  redis:
    host: 47.106.95.195
    port: 6379
    database: 0
    jedis:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1
        time-between-eviction-runs: 6000
    timeout: 10000
