server:
  port: 80
  servlet:
    context-path: /
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
    cache: false
    servlet:
      content-type: text/html
justauth:
  enabled: true
  type:
    wechat_mp:
      client-id: wxbfbbd81f76996e00
      client-secret: bdf2ce1a8a8ce5583830c04ea15da324
      redirect-uri: http://sudk.top/oauth/wechat_mp/callback
    wechat_open:
      client-id: wx5e8811c7abc2685c
      client-secret: 6e2b5997c0b0e106c59f90d442da12eb
      redirect-uri: http://sudk.top/oauth/wechat_open/callback
    alipay:
      client-id: 2021001130681977
      client-secret: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCTN+Z7U0F46w/8esRE/wUTniVkBrAhV+8XpajHGl1jS7r3jgPt8LtgGPNfDd8sH37kSNsvOTnIbLisR9K+TfSpe1bTuamxG9yAChtCKI6QwW9lPDF8np4jNjddFq+mpzM4frmtAEaN+SEzAh5QckYHdBcRy4j/ZjLt9kI8VmSg6BpimGooi5fi986XhkD6PEMQ+XPINLxnYSUchUK6iddrhu53nBvCQwhtMieSz82xxrhnKNSQhWpJLqjoUtf+WnfU5r/eklFbykRhNvnVD2F6JJBS5HhYXklOMEdvIX7dZihFkFs/a0GT/DgSA/ZiQtUEwUmaLRXo7mEfE1TVL3UfAgMBAAECggEBAJCSeeYsWYSMmrNgQHRdWDfuu1ticf8corC/P2Lfkkxb520KavN00B3MAtwa/EoRWASJQ645bXRUyHpvQhce6SCy/g6IKovCB6U5x5EN0Qt42pM5LIPsJPIBYRcqmy52zgcx89dgCOmNeTvlXa20uu7A45LXJV9ilqs3hc5JLSMRppWa7i3+mmFJexBt2dieyFjZvkBiFf123vcXzrjZy4Br8VaQXnQs6wzdDLSh/nYHjd+t7eFTBZ5aaCjBXiQuXXqV2lzCJ4Zhu68d18AvCfrhudLewO4w0U4mY+3JxhDzAFETfiSuGcv52URlQQk/wrg+lUZuw3OQKKR1DDMFk1ECgYEA7xuk/cz+ya7FW8HfWeE3hKYdGTJe78RqclY3ljCvyMXZ6UN/eh4Q26+g1jYkNrNvHAPprupf5oPXss5ec4p3Mq/V6peWtuxysfTfExeL5VHCk8iZOKupjmyspzedbJ94fWa5cpaJC2+bXB2eCvf9AEykO/iatH46SJtWhbk28WcCgYEAnZ5l9i5J7Vh8bqJufnmG04ZFSOt9RTzlkZbDU6aEVSmqa3zfdFpuqZ3svBi3dnzeUdQ3vxA9ZJy1H4MvryjQmqpPG6Xpihm0lgD0pIQCTxY9382TAMaS6ejERl9DG7W8bz+kKR4Quoj/1aANm/Z5ou83FtDIZuebwWaaKiuRc4kCgYEAmniuj7S2yc7Z+5x1UdiZCF5UoCmVgarP5gvjH2lWtwty6yrLGTaBR5vf+WPC43/qgRvaBUGvMPnuCLsf8975gMpuFX9XQ9ffhS4gS3JD06ONY/INYror8TIuHF1mm30u1zzdA7VS1guFP+52YrmxPldFJuVF9OMzfiK0s/FjGHMCgYAvoRn2lm5IhqCzXeo91cNkUALH0kF8lrZYlFJaCMucYIbbDFUJ9/nQz6QmAuINsBYObC6cUe/7Y09oQmA6cf73fdeB51T3ImVrnsZOoIWCGJqB8sElTtw+StRk34yL5xMWGwkkU62CcLu+dismogiHr/nZryWf0wVCIBsd+yRs4QKBgAkCravsdm1Ir+y47MjTK+vwKA7J3lsZTO5V58MNKZ27mN/jvmJ2gIfVAdAK1/+fUTcXz9qej+VGXDJaI3L2wcjP+Ycto6vBkWc5P0UMctb6oDZXTZ/91ocLOukb/ibrHS1MlQd/pEV6zXKjTa1Uie2wWKhA28eBoTvfFRnRxC6X
      alipay-publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAku4ngOG1G6U9+A8HxE9Hh42nRqlV7Hpv7qmGSX7YQWmRsBMTbCYeylL0LvbFOYnMYl6VRdpq3ILNjKpvgQ0zGm5S9g/tbOelk7rwEllssSQxa59yen9+MeCh0MQjiKliQUyUv++s2obWjd0+k2oOprfL2DO1kazNtZVa5PNI7V4eWwOU0t84N71gq/PQ3lyzu4lMnYB4KXl7f41vGwoeXUBsl8rLxaJ+oFk6s+cRRh708kpRKIkwX8jLkC9qKmHTyxEN0I+wi2YqwRcS4z4yKruP2bDWcKgW5vHeDOtL02vK4bv6I2jmOV8GgWBlMQYGX97nB0IMd9GHXB3Hb1sn/QIDAQAB
      redirect-uri: http://sudk.top/oauth/alipay/callback
    github:
      client-id: e0676abf3eae0226fc47
      client-secret: e879430f63264dcd3a3b23159e68deaf159d5bf4
      redirect-uri: http://sudk.top/oauth/github/callback
    qq:
      client-id: 101856504
      client-secret: d4a78e147cb5ed97c7abf0944a9f6005
      redirect-uri: http://sudk.top/oauth/qq/callback


  cache:
    type: default

