spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://47.106.95.195:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false


# mybatis plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.we.springboot.excel.bean
  configuration:
    map-underscore-to-camel-case: true #属性支持驼峰命名
    callSettersOnNulls: true
    cache-enabled: false
  type-handlers-package: com.we.springboot.excel.handler