leelencloud:
  system: pms


spring:
  datasource:
    name: dev
    url: jdbc:mysql://sudk.top:3306/leelendb?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

# mybatis plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.we.springboot.starter.bean
  configuration:
    map-underscore-to-camel-case: true #属性支持驼峰命名
    callSettersOnNulls: true
    cache-enabled: false

