
spring:
  application:
    name: rabbitmq
  rabbitmq:
    host: sudk.top
    port: 5672
    username: root
    password: 123456
    listener:
      simple:
        acknowledge-mode: manual # 手动ACK 不开启自动ACK模式,目的是防止报错后未正确处理消息丢失 默认 为 none

server:
  servlet:
    context-path: /${spring.application.name}
  port: 8888