spring:
  application:
    name: shiro
  datasource:
    schema: classpath:db/*.sql
    initialization-mode: never
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.106.95.195:3306/spring?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  thymeleaf:
    cache: false

# mybatis plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.we.springboot.shiro.bean
  configuration:
    map-underscore-to-camel-case: true #属性支持驼峰命名
    callSettersOnNulls: true
    cache-enabled: false
